# Generated by Django 4.2.4 on 2023-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_due_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.CheckConstraint(check=models.Q(('priority__lte', 3)), name='priority_max_3'),
        ),
    ]
