# Generated by Django 4.2.4 on 2023-09-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_priority_max_3'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='todo',
            name='priority_max_3',
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
